### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/marcoluqueh-Post-Instagram-Clase-1-#1]
# Revisión - Aprobado
- [x] Estilo de código y limpieza
# Feedback
- ¡Buen trabajo. Felicidades @marcoluqueh !
## Estilo de código y limpieza
- ¡Muy bien hecho!
## Mejores prácticas/comentarios
- Es una buena práctica colocar los recursos como imágenes en una carpeta separada "img" (por ejemplo) para tener mejor organizado el proyecto. Esto facilita la gestión de los archivos y hace que sea más claro dónde encontrar recursos específicos en el futuro.

**Comment by marcoluqueh** [comment]
¡Entendido Edu! Gracias por el feedback 😊

**Comment by EduardoHernandezGuzman** [comment]
¡Muy buen primer proyecto!
